### ISSUE TITLE
Зачем нужен AsEnumerable ?

### ISSUE THREAD

**Issue by aorgish** [VladKRP/BestTickets#1]
https://github.com/VladKRP/BestTickets/blob/master/BestTickets/BestTickets/Controllers/HomeController.cs#L52

**Comment by qlminspire** [comment]
Я просто во вьюхе использовал тип ienumerable, поэтому делал явное приведение.
https://github.com/VladKRP/BestTickets/blob/master/BestTickets/BestTickets/Views/Home/_Top10FrequentRequests.cshtml#L1

**Comment by qlminspire** [comment]
Но насколько я понял, он не совсем для этого предназначен. Один из возможных вариантов, для вызова стандартного linq методе, при создании в классе метода с названием, аналогичным Linq методу.
